version: 0.2

env:
  variables:
    BS_FOLDER: "apps"
    BS_URL: "pure-base-react-project"

phases:
  install:
    commands:
      - pip3 install --upgrade awscli
      - npm install
      - LIVE_PUBLIC_PATH=$PUBLIC_PATH/$BS_FOLDER/$BS_URL
      - npm run live
      - aws s3 sync --delete dist/ $APP_BUCKET/$BS_FOLDER/$BS_URL